name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]  # Ejecutar cuando haya un push al branch 'main'
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde la pestaña de Actions

permissions:
  contents: read  # Permite leer el contenido del repositorio
  pages: write    # Permite escribir en las páginas de GitHub
  id-token: write # Permite escribir el token de ID

concurrency:
  group: "pages"     # Define un grupo de concurrencia para las acciones
  cancel-in-progress: false  # No cancela las ejecuciones previas si hay una nueva en progreso

jobs:
  build:
    runs-on: ubuntu-latest  # Usar un contenedor de Ubuntu para el entorno de trabajo
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Hacer checkout del código del repositorio

      - name: Setup Node
        uses: actions/setup-node@v4  # Configurar el entorno de Node.js
        with:
          node-version: "20"  # Usar la versión 20 de Node.js
          cache: "npm"  # Activar el caché de npm para mejorar el tiempo de construcción

      - name: Install dependencies
        run: npm install  # Instalar las dependencias del proyecto

      - name: Build with Next.js
        run: npm run build  # Ejecutar el build, ya no es necesario exportar manualmente

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # Subir los archivos generados
        with:
          path: ./out  # Directorio donde Next.js coloca los archivos exportados

  deploy:
    environment:
      name: github-pages  # Definir el entorno como GitHub Pages
      url: ${{ steps.deployment.outputs.page_url }}  # URL de la página desplegada

    runs-on: ubuntu-latest  # Usar Ubuntu para el entorno de despliegue
    needs: build  # Asegurarse de que la construcción haya terminado antes de desplegar
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Desplegar los archivos generados a GitHub Pages
